# Generated by Django 4.1.7 on 2023-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('engineer_cost', models.FloatField()),
                ('architect_cost', models.FloatField()),
                ('manager_cost', models.FloatField()),
                ('tech_writer_cost', models.FloatField()),
                ('manager_coef', models.FloatField()),
                ('tech_writer_coef', models.FloatField()),
            ],
        ),
    ]
