# Generated by Django 4.1.7 on 2023-05-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontractor',
            old_name='jobs',
            new_name='subcontract_jobs',
        ),
        migrations.RenameField(
            model_name='subcontractor',
            old_name='name',
            new_name='subcontract_name',
        ),
        migrations.RenameField(
            model_name='subcontractor',
            old_name='price',
            new_name='subcontract_price',
        ),
    ]
