# Generated by Django 4.1.7 on 2023-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('summa_with_nds', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('labor_cost_person', models.FloatField(null=True)),
                ('labor_cost_mp', models.FloatField(null=True)),
                ('labor_cost_rtd', models.FloatField(null=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
