# Generated by Django 4.1.7 on 2023-05-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesstrip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='tech_writer_cost',
        ),
    ]
