# Generated by Django 4.1.7 on 2023-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesstrip', '0002_remove_businesstrip_tech_writer_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='duration',
            new_name='duration_trip',
        ),
    ]
